<?php
require_once("../controllers/EmpleadoController.php");
require_once("../controllers/UserController.php");
require_once("../controllers/EstadoController.php");
require_once("../controllers/SocioController.php");
require_once("../controllers/ActividadController.php");
require_once("../controllers/CiudadController.php");
require_once("../controllers/VehiculosController.php");
require_once("../controllers/LaborController.php");
require_once("../controllers/ZonasController.php");
require_once("../controllers/CarroBarridoController.php");
require_once("../controllers/MecanicaController.php");
require_once("../controllers/AreasPublicasController.php");
require_once("../controllers/DisposicionController.php");
require_once("../controllers/RecoleccionController.php");
require_once("../controllers/EmpresaController.php");
require_once("../controllers/RutasController.php");